branchName: short
 autoCloseIssue: true
 branches:
   - label: docs📝
     prefix: docs/
   - label: hotfix🚑
     prefix: hotfix/
   - label: refactor♻️
     prefix: refactor/
   - label: env🔧
     prefix: chore/
   - label: release👷
     prefix: release/
   - label: test✅
     prefix: test/
   - label: bug🐛
     prefix: fix/
   - label: feature✨
     prefix: feat/
   - label: question🏷️
     skip: true
   - label: '*'
     skip: true
 commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
 copyIssueLabelsToPR: true
 copyIssueAssigneeToPR: true
 copyIssueProjectsToPR: true
 copyIssueMilestoneToPR: true
